In [ ]:
# 1 * Numpy is a nultuim arraya

In [ ]:
import math

math.sqrt(4)



In [ ]:
! pip install numpy

In [ ]:
! pip install numpy

In [ ]:
import math
math.sqrt(16)

In [ ]:
type(np4tn)

In [ ]:
l1 = [21,12,'hello world']

In [ ]:
type(l1)

converting python list to numpy array

In [ ]:
np.array(l1)

In [ ]:
type(l1)

In [ ]:
np.array(l1)

In [ ]:
l2 = np.array

In [ ]:
arr1 = np.array([1,2,3,4,5,'hello world'])

In [ ]:
type(arr1)

In [ ]:
np.array([[1,3,2,1],
       [4,3,2,1]])

In [ ]:
b = np.array([[1,3,2,1],
              [4,3,2,1]])
b.shape

In [11]:
b[0,1:3]=[2,3]

In [12]:
b

array([[1. , 2. , 3. , 5.8],
       [2.1, 3. , 4.2, 4.5]])

In [13]:
b.itemsize*b.size

64

In [14]:
np.int64(3)

np.int64(3)

In [ ]:
l = [1,2,3,4,5,5]

In [15]:
l = [1,2,3,4,5,5]
l[1:3]

[2, 3]

In [ ]:
#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)

In [1]:
import numpy as np

In [17]:
#initialize array
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

one dimensional array : [1 2 3]


In [18]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [19]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)

dimension of a : 1
dimension of b : 2


In [20]:
#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)

shape of a : (3,)
shape of b : (2, 4)


In [21]:
#Get  Type
print("a type is :",a.dtype)

a type is : int16


In [22]:
#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;

size of a : 3


In [23]:

#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)

a item size : 2
total size is a: 6


In [24]:
#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

In [25]:
#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]


np.float64(4.2)

In [26]:

#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);

row : [2.1]


In [27]:
#Get specific column[:,column]
print("column :",b[:,1])

column : [2. 3.]


In [28]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])


subset of specific row [3.  4.5]


In [29]:
#change element
b[1,2]=8
print(b)

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


In [30]:
b[:,2]=[9,4]
b

array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

3-d exmaple

In [31]:
c=np.array([[
[1,2],[3,4]
  ],
  [
      [5,6],[7,8]
  ]
])
   


In [32]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
 type(c)

numpy.ndarray

In [35]:
c.shape

(2, 2, 2)

In [37]:
c.size


8

## calculate the memory space took for c numpy array

In [39]:
c.dtype

dtype('int64')

In [40]:
c.itemsize * c.size

64

In [42]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [43]:
#get specific element (work outside in)
print("specified element is :",c[0,1,1])

specified element is : 4


In [52]:
zm = np.zeros((3,4)) #3 rows and 4 columns

In [53]:
zm.ndim

2

In [54]:
zm.shape

(3, 4)

All 1's matrixs

In [58]:
np.ones ((3,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
#Any other number
np.full((4,5),100,dtype="float")

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [70]:
np.full_like(100,200,dtype="float")


array(200.)

Random matrixs

In [71]:
np.random.random_sample((2,3))

array([[0.64980998, 0.35873352, 0.15783363],
       [0.56254201, 0.35289784, 0.95905928]])

In [73]:
np.random.rand(2,3)

array([[0.22593619, 0.0010927 , 0.8975448 ],
       [0.83843156, 0.65728537, 0.15329212]])

In [74]:
np.random.randint(2,9,size=(3,3))

array([[6, 7, 7],
       [5, 8, 3],
       [6, 5, 8]], dtype=int32)

In [75]:
#Generate identity matrix only one argument bcoz identity matrix is a
np.identity(0)# 5,5''

array([], shape=(0, 0), dtype=float64)